### PR TITLE
Delete Vault Item

### PR DESCRIPTION
**Pull request by angieyeh**
## Changes
- Add API request for delete vault item
  - This was tested with sample data set since ability to create new items in progress
  - API call works as we see the snackbar that shows the call was unsuccessful
- Change create vault item layout so TextFields are full width 
- Add ability to close modal when clicking outside the modal
- Moved the New button to the Dashboard page from VaultItemTiles
- Add icon adornments to password field for visibility and copy functionality 
- State is not being updated. That will depend on the library @derthadams is working on to update the state

https://github.com/secure-password-manager/PasswordManagerWeb/assets/14142356/a80a54d7-b899-4ba7-9466-e9aef00a8cff

https://github.com/secure-password-manager/PasswordManagerWeb/assets/14142356/d24f92f3-edca-4dfb-8515-697baa082f79

Screen Shot 2023-11-30 at 12 27 57

### CODE REVIEW

**Review by dtrannam — APPROVED** [review]
Looks good! We can adjust the password generator forms a bit to align it better, but that can come later if we have more time

**Comment by angieyeh** [comment]
@dtrannam I originally moved the username input field down to align with the password input field, but that looked weird because there's too much extra space. I was thinking I could move the random pw generator icon below the password input field, but haven't tried it yet. How do you think we should adjust the layout to account for the extra icon?

**Comment by derthadams** [comment]
> How do you think we should adjust the layout to account for the extra icon?

Would it be easy to rework this form so that all of the fields are full-width (like the VaultItemPopOut)? Then all of the extra icons (including the compromised password checker) would fit in the field itself.

**Comment by angieyeh** [comment]
@derthadams Working on making the layout change. Styling  the pw generator component is more effort with the extra icon. I was thinking of adding the icon as an adornment, but I think 4 is probably too many?

**Pull request merged**
